In [1]:
import torch

# 创建Tensor

参考链接：https://blog.csdn.net/CltCj/article/details/120060543?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522168190136416782427496302%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=168190136416782427496302&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~top_positive~default-1-120060543-null-null.142^v85^koosearch_v1,239^v2^insert_chatgpt&utm_term=pytorch&spm=1018.2226.3001.4187

torch.FloatTensor生成数据类型为浮点型的Tensor,参数可以是列表，也可以是一个维度

In [2]:
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([2,3,4,5])
a,b

(tensor([[-7.6894e-23,  9.3186e-43, -7.6894e-23],
         [ 9.3186e-43, -7.6872e-23,  9.3186e-43]]),
 tensor([2., 3., 4., 5.]))

torch.IntTensor用于生成数据类型为整型的Tensor,传递给传递给torch.IntTensor的参数可以是列表，也可以是一个维度值。

In [3]:
a = torch.IntTensor(2,3)
b = torch.IntTensor([6,7,8,9])
a,b

(tensor([[-1699091616,         665, -1699091632],
         [        665, -1699095216,         665]], dtype=torch.int32),
 tensor([6, 7, 8, 9], dtype=torch.int32))

torch.rand用于生成一个随机数tensor

In [ ]:
a = torch.rand(2,3)
a 

torch.randn用于生成数据类型为浮点数且维度指定的随机Tensor，随机生成的浮点数的取值满足均值为0，方差为1的正态分布

In [ ]:
a = torch.randn(2,3)
a 

torch.range用于生成数据类型为浮点型且起始范围和结束范围的Tensor,所以传递给torch.range的参数有三个，分别为起始值，结束值，步长，其中步长用于指定从起始值到结束值得每步的数据间隔。

In [ ]:

a = torch.range(1,20,2)
a

# Tensor运算

abs将参数传递到torch.abs后返回输入参数的绝对值作为输出，输入参数必须是一个Tensor数据类型的变量

In [3]:
a = torch.randn(2,3)
b = torch.abs(a)
b

tensor([[0.0277, 0.4401, 1.8545],
        [0.6162, 1.1254, 0.2220]])

add将参数传递到torch.add后返回输入参数的求和结果作为输出，输入参数既可以全部是Tensor数据类型的变量，也可以一个是Tensor数据类型的变量，另一个是标量

In [4]:
c = torch.add(a,b)
c

tensor([[0.0553, 0.0000, 3.7090],
        [1.2323, 0.0000, 0.4441]])

In [ ]:
e = torch.add(d,10)
e

torch.clamp是对输入参数按照自定义的范围进行裁剪，最后将参数裁剪的结果作为输出，所以输入参数一共有三个，分别是需要进行裁剪的Tensor数据类型的变量、裁剪的上上边界和裁剪的下边界，具体的裁剪过程是：使用变量中的每个元素分别和裁剪的上边界及裁剪的下边界的值进行比较，如果元素的值小于裁剪的下边界的值，该元素被重写成裁剪的下边界的值；同理，如果元素的值大于裁剪的上边界的值，该元素就被重写成裁剪的上边界的值。

In [5]:
a = torch.randn(2,3)
a

tensor([[-0.7101,  0.3636, -1.3875],
        [ 0.1313,  1.1783,  1.7988]])

In [6]:
b = torch.clamp(a,-0.1,0.1)
b

tensor([[-0.1000,  0.1000, -0.1000],
        [ 0.1000,  0.1000,  0.1000]])

torch.div是将参数传递到torch.div后返回输入参数的求商结果作为输出，同样，参与运算的参数可以全部是Tensor数据类型的变量，也可以是Tensor数据类型的变量和标量的组合。

In [9]:
a = torch.randn(2,3)
print('a=',a)
b = torch.randn(2,3)
print('b=',b)
c = torch.div(a,b)
print('c=',c)

a= tensor([[ 0.4968,  1.4927,  1.0485],
        [ 0.7948, -1.0124,  0.3874]])
b= tensor([[ 0.4536, -0.6836, -1.3328],
        [-1.0853,  0.8443,  0.9291]])
c= tensor([[ 1.0953, -2.1836, -0.7867],
        [-0.7323, -1.1991,  0.4170]])


torch.pow将参数传递到torch.pow后返回输入参数的求幂结果作为输出，参与运算的参数可以全部是Tensor数据类型的变量，也可以是Tensor数据类型的变量和标量的组合。

In [10]:
a = torch.randn(2,3)
print('a=',a)
b = torch.pow(a,2)
print('b=',b)

a= tensor([[ 1.3761,  0.7744, -1.0337],
        [ 2.3221, -0.3241, -0.9173]])
b= tensor([[1.8936, 0.5998, 1.0686],
        [5.3922, 0.1050, 0.8414]])


<mark>torch.mm(矩阵相乘)：将参数传递到torch.mm后返回输入参数的求积结果作为输出，不过这个求积的方式和之前的torch.mul运算方式不太一样，torch.mm运用矩阵之间的乘法规则进行计算，所以被传入的参数会被当作矩阵进行处理，参数的维度自然也要满足矩阵乘法的前提条件，即前一个矩阵的行数必须和后一个矩阵列数相等</mark>

In [12]:
a = torch.randn(2,3)
print('a=',a)
b = torch.randn(3,2)
print('b=',b)
c = torch.mm(a,b)
print('c=',c)

a= tensor([[-1.7425,  0.5714,  0.4391],
        [ 1.0334, -0.8574,  0.3706]])
b= tensor([[-0.1050,  2.6510],
        [-1.3000,  1.3820],
        [-0.1282,  0.2522]])
c= tensor([[-0.6161, -3.7191],
        [ 0.9586,  1.6481]])


torch.mv(矩阵与向量相乘)将参数传递到torch.mv后返回输入参数的求积结果作为输出，torch.mv运用矩阵与向量之间的乘法规则进行计算，被传入的第1个参数代表矩阵，第2个参数代表向量，循序不能颠倒。

In [13]:
a = torch.randn(2,3)
print('a=',a)
b = torch.randn(3)
print('b=',b)
c = torch.mv(a,b)
print('c=',c)

a= tensor([[-0.2882, -2.4091, -1.0590],
        [-0.2536,  0.9526, -0.7067]])
b= tensor([0.3941, 1.4146, 0.7654])
c= tensor([-4.3320,  0.7067])
